version: "3.2"

services:
  pacta_dash:
    container_name: pacta_dash_prototype
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: 'root'
    ports:
      - '3838:3838'
    volumes:
      - /Users/jdhoffa/github/pacta-data:/pacta-data
      - /Users/jdhoffa/github/workflow.transition.monitor/working_dir:/bound/working_dir
      - /Users/jdhoffa/github/templates.transition.monitor/:/templates.transition.monitor
      - 'shiny_logs:/var/log/shiny-server'

volumes:
  shiny_logs:
